package com.cafe.erp.identity.domain.model;

public enum ActionType {
    LOGIN, LOGOUT,
    CREATE_ORDER, CANCEL_ORDER, VOID_ORDER_LINE,
    APPLY_DISCOUNT, APPLY_PROMO,
    OPEN_SHIFT, CLOSE_SHIFT,
    ADD_EXPENSE, PROCESS_PAYMENT,
    START_SESSION, END_SESSION,
    PRICE_CHANGE, CREATE_PROMO, TOGGLE_PROMO,
    OPEN_DRAWER, STOCK_ADJUSTMENT, OTHER
}
